name: 'Docker Sync Action'
description: 'Keeps docker images in sync between registries or repositories'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  source:
    description: source image repository
    required: true
  destination:
    description: destination image repository
    required: true
  max-tags:
    description: The maximum number of image tags to sync
    required: false
    default: '10'

runs:
  using: composite
  steps:
  - name: Install regctl
    uses: iarekylew00t/regctl-installer@v1.2
  - name: Sync images
    shell: bash
    run: |
      set -e -o pipefail
      skopeo --version

      VERSIONS="$(skopeo list-tags docker://${{ inputs.source }} | jq -r ".Tags[]" | sort --version-sort | tail -n ${{ inputs.max-tags }})"

      echo "${VERSIONS}" | while read version ; do

          if [ "$version" = "" ]; then
              break
          fi

          # Only copy if it isn't there already.
          skopeo inspect docker://${{ inputs.destination }}:$version >/dev/null 2>&1
          image_exists=$?

          if [ "$image_exists" = "0" ]; then
              break
          fi

          regctl image copy \
              ${{ inputs.source }}:$version \
              ${{ inputs.destination }}:$version
      done

