name: Docker Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 10 * * *"

jobs:
  docker-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker-repo:
        - sonatype/nexus3
        - loopingz/smtp-relay
        - tonistiigi/binfmt

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - id: repo
        run: |
          echo "name=$(echo ${{ matrix.docker-repo }} | cut -d'/' -f1)" >> $GITHUB_OUTPUT

      - name: Sync ${{ matrix.docker-repo }} images
        uses: titenkov/docker-sync-action@v1
        with:
          source: ${{ matrix.docker-repo }}
          destination: ghcr.io/${{ github.repository_owner }}/${{ steps.repo.outputs.name }}
          destination-credentials: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}





