on:
  workflow_dispatch: {}

jobs:
  docker-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker-repo:
        - sonatype/nexus3
        - loopingz/smtp-relay
        - tonistiigi/binfmt

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync ${{ matrix.docker-repo }} images
        uses: titenkov/docker-sync-action@v1
        with:
          source: ${{ matrix.docker-repo }}
          destination: ghcr.io/portswigger-cloud/${{ matrix.docker-repo }}
          destination-credentials: titenkov:${{ secrets.GH_TOKEN }}





