name: ECR Sync

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"

jobs:
  docker-sync:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ecr-repo:
          - web-server
          - enterprise-server
          - enterprise-scan-container
          - portswigger-hosted-scan
          - scan-controller
          - relay

    permissions:
      actions: read
      contents: read
    env:
      FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
    steps:
      - run: "echo $FAKE_SECRET"
      - uses: portswigger-tim/safer-runner-action@0d9a798b9ddea4a6b9ab3c4375f8018b191c2e3d # v1.1.2
        with:
          mode: enforce
          allowed-domains: |
            auth.docker.io
            production.cloudflare.docker.com
            public.ecr.aws
            registry-1.docker.io
            d2glxqk2uabbnd.cloudfront.net
            d5l0dvt14r5h8.cloudfront.net
          disable-sudo: true
          disable-docker: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Sync ${{ matrix.ecr-repo }} images
        uses: portswigger-cloud/docker-sync/.github/actions/docker-sync@main
        with:
          max-tags: '20'
          source: public.ecr.aws/portswigger/${{ matrix.ecr-repo }}
          destination: portswigger/${{ matrix.ecr-repo }}
